# .github/release.yml

name: Release on npm
on:
  push:
    branches:
      - "modou"
    paths:
      - package.json

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true

      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Checkout zod-deno
        uses: actions/checkout@v3
        with:
          path: deno/lib

      - name: Install dependencies
        run: |
          yarn install

      - name: Build
        run: |
          yarn clean
          yarn build
          cp logo.svg deno/lib
          cp README.md deno/lib

      - id: publish
        name: Publish to NPM
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          dry-run: false
          access: public




